# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vbet.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(857, 848)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.label_stream = QtWidgets.QLabel(Dialog)
        self.label_stream.setObjectName("label_stream")
        self.verticalLayout_6.addWidget(self.label_stream)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.label_DEM = QtWidgets.QLabel(Dialog)
        self.label_DEM.setObjectName("label_DEM")
        self.verticalLayout_6.addWidget(self.label_DEM)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.label_scratch = QtWidgets.QLabel(Dialog)
        self.label_scratch.setObjectName("label_scratch")
        self.verticalLayout_6.addWidget(self.label_scratch)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.label_da = QtWidgets.QLabel(Dialog)
        self.label_da.setObjectName("label_da")
        self.verticalLayout_6.addWidget(self.label_da)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.label_output = QtWidgets.QLabel(Dialog)
        self.label_output.setObjectName("label_output")
        self.verticalLayout_6.addWidget(self.label_output)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.lineEdit_stream = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_stream.setObjectName("lineEdit_stream")
        self.verticalLayout_7.addWidget(self.lineEdit_stream)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.lineEdit_DEM = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_DEM.setObjectName("lineEdit_DEM")
        self.verticalLayout_7.addWidget(self.lineEdit_DEM)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.lineEdit_scratch = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_scratch.setObjectName("lineEdit_scratch")
        self.verticalLayout_7.addWidget(self.lineEdit_scratch)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.lineEdit_da = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_da.setObjectName("lineEdit_da")
        self.verticalLayout_7.addWidget(self.lineEdit_da)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.lineEdit_output = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.verticalLayout_7.addWidget(self.lineEdit_output)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem13)
        self.pushButton_stream = QtWidgets.QPushButton(Dialog)
        self.pushButton_stream.setObjectName("pushButton_stream")
        self.verticalLayout_8.addWidget(self.pushButton_stream)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.pushButton_DEM = QtWidgets.QPushButton(Dialog)
        self.pushButton_DEM.setObjectName("pushButton_DEM")
        self.verticalLayout_8.addWidget(self.pushButton_DEM)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem15)
        self.pushButton_scratch = QtWidgets.QPushButton(Dialog)
        self.pushButton_scratch.setObjectName("pushButton_scratch")
        self.verticalLayout_8.addWidget(self.pushButton_scratch)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.pushButton_da = QtWidgets.QPushButton(Dialog)
        self.pushButton_da.setObjectName("pushButton_da")
        self.verticalLayout_8.addWidget(self.pushButton_da)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.pushButton_output = QtWidgets.QPushButton(Dialog)
        self.pushButton_output.setObjectName("pushButton_output")
        self.verticalLayout_8.addWidget(self.pushButton_output)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_exda = QtWidgets.QLabel(Dialog)
        self.label_exda.setObjectName("label_exda")
        self.verticalLayout_3.addWidget(self.label_exda)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem21)
        self.label_lgda = QtWidgets.QLabel(Dialog)
        self.label_lgda.setObjectName("label_lgda")
        self.verticalLayout_3.addWidget(self.label_lgda)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem22)
        self.label_medda = QtWidgets.QLabel(Dialog)
        self.label_medda.setObjectName("label_medda")
        self.verticalLayout_3.addWidget(self.label_medda)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem23)
        self.label_lgslope = QtWidgets.QLabel(Dialog)
        self.label_lgslope.setObjectName("label_lgslope")
        self.verticalLayout_3.addWidget(self.label_lgslope)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem24)
        self.label_medslope = QtWidgets.QLabel(Dialog)
        self.label_medslope.setObjectName("label_medslope")
        self.verticalLayout_3.addWidget(self.label_medslope)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem25)
        self.label_smslope = QtWidgets.QLabel(Dialog)
        self.label_smslope.setObjectName("label_smslope")
        self.verticalLayout_3.addWidget(self.label_smslope)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem26)
        self.label_lgbuf = QtWidgets.QLabel(Dialog)
        self.label_lgbuf.setObjectName("label_lgbuf")
        self.verticalLayout_3.addWidget(self.label_lgbuf)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem27)
        self.label_medbuf = QtWidgets.QLabel(Dialog)
        self.label_medbuf.setObjectName("label_medbuf")
        self.verticalLayout_3.addWidget(self.label_medbuf)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem28)
        self.label_smbuf = QtWidgets.QLabel(Dialog)
        self.label_smbuf.setObjectName("label_smbuf")
        self.verticalLayout_3.addWidget(self.label_smbuf)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem29)
        self.label_minbuf = QtWidgets.QLabel(Dialog)
        self.label_minbuf.setObjectName("label_minbuf")
        self.verticalLayout_3.addWidget(self.label_minbuf)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem30)
        self.label_lgdepth = QtWidgets.QLabel(Dialog)
        self.label_lgdepth.setObjectName("label_lgdepth")
        self.verticalLayout_3.addWidget(self.label_lgdepth)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem31)
        self.label_meddepth = QtWidgets.QLabel(Dialog)
        self.label_meddepth.setObjectName("label_meddepth")
        self.verticalLayout_3.addWidget(self.label_meddepth)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem32)
        self.label_smdepth = QtWidgets.QLabel(Dialog)
        self.label_smdepth.setObjectName("label_smdepth")
        self.verticalLayout_3.addWidget(self.label_smdepth)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem33)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_exda = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_exda.setObjectName("lineEdit_exda")
        self.verticalLayout.addWidget(self.lineEdit_exda)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem34)
        self.lineEdit_lgda = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_lgda.setClearButtonEnabled(False)
        self.lineEdit_lgda.setObjectName("lineEdit_lgda")
        self.lineEdit_lgda.setValidator(QtGui.QDoubleValidator())
        self.lineEdit_lgda.setText(str(250))
        self.verticalLayout.addWidget(self.lineEdit_lgda)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem35)
        self.lineEdit_medda = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_medda.setObjectName("lineEdit_medda")
        self.lineEdit_medda.setValidator(QtGui.QDoubleValidator())
        self.lineEdit_medda.setText(str(25))
        self.verticalLayout.addWidget(self.lineEdit_medda)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem36)
        self.SpinBox_lgslope = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_lgslope.setProperty("value", 3.0)
        self.SpinBox_lgslope.setObjectName("SpinBox_lgslope")
        self.verticalLayout.addWidget(self.SpinBox_lgslope)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem37)
        self.SpinBox_medslope = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_medslope.setProperty("value", 4.0)
        self.SpinBox_medslope.setObjectName("SpinBox_medslope")
        self.verticalLayout.addWidget(self.SpinBox_medslope)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem38)
        self.SpinBox_smslope = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_smslope.setProperty("value", 5.0)
        self.SpinBox_smslope.setObjectName("SpinBox_smslope")
        self.verticalLayout.addWidget(self.SpinBox_smslope)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem39)
        self.lineEdit_lgbuf = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_lgbuf.setObjectName("lineEdit_lgbuf")
        self.lineEdit_lgbuf.setValidator(QtGui.QDoubleValidator())
        self.verticalLayout.addWidget(self.lineEdit_lgbuf)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem40)
        self.lineEdit_medbuf = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_medbuf.setObjectName("lineEdit_medbuf")
        self.lineEdit_medbuf.setValidator(QtGui.QDoubleValidator())
        self.verticalLayout.addWidget(self.lineEdit_medbuf)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem41)
        self.lineEdit_smbuf = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_smbuf.setObjectName("lineEdit_smbuf")
        self.lineEdit_smbuf.setValidator(QtGui.QDoubleValidator())
        self.verticalLayout.addWidget(self.lineEdit_smbuf)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem42)
        self.lineEdit_minbuf = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_minbuf.setObjectName("lineEdit_minbuf")
        self.lineEdit_minbuf.setValidator(QtGui.QDoubleValidator())
        self.verticalLayout.addWidget(self.lineEdit_minbuf)
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem43)
        self.SpinBox_lgdepth = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_lgdepth.setProperty("value", 4.0)
        self.SpinBox_lgdepth.setObjectName("SpinBox_lgdepth")
        self.verticalLayout.addWidget(self.SpinBox_lgdepth)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem44)
        self.SpinBox_meddepth = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_meddepth.setProperty("value", 2.0)
        self.SpinBox_meddepth.setObjectName("SpinBox_meddepth")
        self.verticalLayout.addWidget(self.SpinBox_meddepth)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem45)
        self.SpinBox_smdepth = QtWidgets.QDoubleSpinBox(Dialog)
        self.SpinBox_smdepth.setProperty("value", 1.5)
        self.SpinBox_smdepth.setObjectName("SpinBox_smdepth")
        self.verticalLayout.addWidget(self.SpinBox_smdepth)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem46)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Valley Bottom Extraction Tool"))
        self.label.setText(_translate("Dialog", "Select file/folder paths:"))
        self.label_stream.setText(_translate("Dialog", "Stream Network (.shp)"))
        self.label_DEM.setText(_translate("Dialog", "Digital Elevation Model (.tif)"))
        self.label_scratch.setText(_translate("Dialog", "Scratch Work Folder"))
        self.label_da.setText(_translate("Dialog", "Drainage Area Raster (.tif)"))
        self.label_output.setText(_translate("Dialog", "Output"))
        self.pushButton_stream.setText(_translate("Dialog", ". . ."))
        self.pushButton_DEM.setText(_translate("Dialog", ". . ."))
        self.pushButton_scratch.setText(_translate("Dialog", ". . ."))
        self.pushButton_da.setText(_translate("Dialog", ". . ."))
        self.pushButton_output.setText(_translate("Dialog", ". . ."))
        self.label_2.setText(_translate("Dialog", "Enter parameter values:"))
        self.label_exda.setText(_translate("Dialog", "Existing Drainage Area Field"))
        self.label_lgda.setText(_translate("Dialog", "Large Drainage Area Threshold"))
        self.label_medda.setText(_translate("Dialog", "Medium Drainage Area Threshold"))
        self.label_lgslope.setText(_translate("Dialog", "Large Slope Threshold"))
        self.label_medslope.setText(_translate("Dialog", "Medium Slope Threshold"))
        self.label_smslope.setText(_translate("Dialog", "Small Slope Threshold"))
        self.label_lgbuf.setText(_translate("Dialog", "Large Buffer"))
        self.label_medbuf.setText(_translate("Dialog", "Medium Buffer"))
        self.label_smbuf.setText(_translate("Dialog", "Small Buffer"))
        self.label_minbuf.setText(_translate("Dialog", "Minimum Buffer"))
        self.label_lgdepth.setText(_translate("Dialog", "Large Depth"))
        self.label_meddepth.setText(_translate("Dialog", "Medium Depth"))
        self.label_smdepth.setText(_translate("Dialog", "Small Depth"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
